# SPDX-License-Identifier: Apache-2.0

name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - '**/.*py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/unit-testing.yml' # This workflow
  pull_request:
    branches:
      - main
    paths:
      - '**/.*py'
      - 'pyproject.toml'
      - 'tox.ini'
      - '.github/workflows/unit-testing.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: "${{ matrix.platform }}"
    strategy:
      matrix:
        python:
          - '3.10'
          - '3.11'
        platform:
          - 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh

      - name: Unit tests
        run: |
          tox

  lint:
    name: "${{ matrix.lint.name }}"
    runs-on: "${{ matrix.platform }}"
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.11'
        platform:
          - 'ubuntu-latest'
        lint:
          - name: 'ruff'
            commands: |
              tox -e ruffcheck
          - name: 'pylint'
            commands: |
              echo "::add-matcher::.github/workflows/matchers/pylint.json"
              tox -e pylint
          - name: 'mypy'
            commands: |
              echo "::add-matcher::.github/workflows/matchers/mypy.json"
              tox -e mypy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh

      - name: "${{ matrix.lint.name }}"
        run: |
          ${{ matrix.lint.commands }}
        env:
          RUFF_OUTPUT_FORMAT: github
